### ISSUE TITLE
Correction in Dockerfile command

### ISSUE THREAD

**Issue by msorens** [DanWahlin/Docker-for-Web-Developers#6]
Following along in section 6, "Building Custom Images with Dockerfile", I went to your Github repo here to grab the Dockerfile but after launching via `docker run...`, then browsing to the website failed. Comparing to your demo in the video, I noticed a discrepancy in this line:
https://github.com/DanWahlin/Docker-for-Web-Developers/blob/5a59e224ab08b5639b80ef339bb59ef5b5cc48b1/Module5-Building_Custom_Images_with_Dockerfile/ExpressSite/Dockerfile#L9

Once I changed that to this...
```
COPY      . /var/www
```
then I could open the test website in the browser.

**Comment by DanWahlin** [comment]
Thanks for contributing that. In this case the following are equivalent:

COPY . /var/www

is the same as:

COPY . .

The reason is that the second "." character is actually /var/www due to the working directory being set right above the COPY statement:

WORKDIR   /var/www

I just tried it out and it seems to be working as expected (which should definitely be the case) but if you let me know the steps you took I am happy to try to help to see why the COPY . . didn't work for you.

**Comment by msorens** [comment]
Thanks, Dan. I thought it should work for the reasons you outlined above so was actually surprised when my change "fixed" it for me. That said, I suspect I did something silly (PEBKAC and all that) that caused the failure in the first place, so not too worried about it. 😁

**Comment by DanWahlin** [comment]
Good deal. I saw the other issue you mentioned as well and will respond there as soon as I get some available time.
